[build-system]
requires = [
    "cmake~=3.24.0",
    "ninja; platform_system!='Windows'",
    "pybind11",
    "setuptools>=42",
    "toml"]

build-backend = "setuptools.build_meta"

[project]
name = "PennyLane-Lightning"
version = "0.37.0-dev52"
description = "PennyLane-Lightning plugin"
readme = "README.rst"
license = {text = "Apache License 2.0"}
maintainers = [
    { name = "Xanadu Inc.", email = "software@xanadu.ai" },
]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Physics",
]

dynamic = ["entry-points", "dependencies"]

[project.optional-dependencies]
gpu = [
    "pennylane-lightning-gpu",
]
kokkos = [
    "pennylane-lightning-kokkos",
]

[project.urls]
Homepage = "https://github.com/PennyLaneAI/pennylane-lightning"
