name: Formatting check
on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  black:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run:
            python -m pip install click==8.0.4 black==23.7.0

      - name: Checkout PennyLane-Lightning
        uses: actions/checkout@v3

      - name: Run Black
        run: black -l 100 pennylane_lightning/ tests/ --check

  format-cpp:
    name: Format (C++)
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt -y install clang-format-14 python3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run formatter
        run: ./bin/format --check --cfversion 14 ./pennylane_lightning/core/src

  tidy-cpp:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        pl_backend: ["lightning_qubit"]

    name: Tidy (C++)
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout PennyLane-Lightning
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: sudo apt update && sudo apt -y install clang-tidy-14 cmake gcc-11 g++-11 ninja-build libomp-14-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Run clang-tidy compilation
        run: |
          cmake -BBuild -G Ninja . \
            -DENABLE_CLANG_TIDY=ON \
            -DCLANG_TIDY_BINARY=clang-tidy-14 \
            -DBUILD_TESTS=ON \
            -DENABLE_WARNINGS=ON \
            -DPL_BACKEND=${{ matrix.pl_backend }} \
            -DCMAKE_CXX_COMPILER="$(which g++-11)" \
            -DCMAKE_C_COMPILER="$(which gcc-11)"
          cmake --build ./Build