name: Testing (GPU)
on:
  pull_request:



concurrency:
  group: tests_gpu-${{ github.ref }}
  cancel-in-progress: true


jobs:
  gpu_test:
    runs-on:
      - self-hosted
      - ubuntu-22.04
      - gpu

    steps:
      - name: Show PATH
        run: |
          set -x
          echo $PATH
          echo $LD_LIBRARY_PATH
          set +x

      - name: Check CUDA binary folder exists
        run: |
          set -x
          ls -ltrh /usr/local
          ls -ltrh /usr/local/cuda
          ls -ltrh /usr/local/cuda/bin
          [ ! -d '/usr/local/cuda/bin' ] && exit 1

      - name: Update PATH to include CUDA
        run: |
          echo '/usr/local/cuda/bin' >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          echo "LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV

      - name: Show PATH (again)
        run: |
          set -x
          echo $PATH
          echo $LD_LIBRARY_PATH
          set +x

      - name: Check nvidia-smi
        run: nvidia-smi

      - name: Check default CUDA
        run: |
          set -x
          which nvcc
          nvcc --version
          set +x

      - name: Try loading CUDA 12.2
        run: |
          source /etc/profile.d/modules.sh
          module use /opt/modules
          
          module load cuda/12.2
          nvcc --version
